public with sharing class Arthimaticcalculations {
    public void add(integer a, integer b){
        integer sum = a+ b ;
        System.debug(sum);
    }
        Public void Addition(integer x , integer y){
        Integer z = x+y;
        System.debug(z);
        }
        Public void subscription (integer x, integer y){
        Integer z = x-y ;
        System.debug(z);
        }
        Public void multiplication (integer x, integer y, integer m){
        Integer z = x * y * m;
        System.debug(z);
}
}
