public class checkDataTypes {
    public void MethodBoolean(){
        boolean checkBoolean=true;
          System.debug(checkBoolean);
    }

    public void MethodInteger(){
        integer varfirst=1;
        integer varsecond=2;
        system.debug(varfirst + varsecond);
    }

    public void Sytringmethod(){
        string Name1= 'Name';
        string Name2='Esra';
        System.debug(Name1);
        System.debug(Name2);
    }
}
