public class PrimitiveDataTypeDemo {
    public void printBasicDataType(){
        //method body

      /* string batchName = 'Falcons 8';
        integer totalCandidates = 40;
        boolean isAdminCompleted = true;

        
        system.debug(batchName);
        system.debug(totalCandidates);
        system.debug(isAdminCompleted);


        string batchDescription = batchName + ' are the best.';
        system.debug(batchDescription);*/
    }
    public void printBasicDataType2(){
    decimal decimalValue = 365.5;
    system.debug('decimal value = '+ decimalValue );
     
    Long longValue = 2147483648L;
    System.debug('long value = ' +longValue);
   
    ID id1 ='0018Z00002f0HxAQAU';
    system.debug('id is ' + id1);
    }


}
