string index2Candidate = ListDemo.candidateList(2);
System.debug('index2Candidate = ' + index2Candidate);

string index5Candidate = ListDemo.candidateList(5);
System.debug('index5Candidate = ' + index5Candidate);

string indexminus5candidate = ListDemo.candidateList(-5);
system.debug(indexminus5candidate);

string index0candidate= ListDemo.candidateList(0);
system.debug(index0candidate);

ListDemo.randomIntegerList();

ListDemo.allCats();
                                    